# Generated by Django 3.2.7 on 2021-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('msg', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='file_index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('file_size', models.CharField(max_length=25)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('signature', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='storage_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('total', models.CharField(max_length=25)),
                ('used', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_file_map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=250)),
                ('user_id', models.IntegerField()),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='ok', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='status',
            field=models.CharField(default='ok', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='age',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pin',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
