# Generated by Django 3.2.7 on 2021-10-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211005_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_index',
            name='signature',
            field=models.CharField(max_length=1000),
        ),
    ]
