# Generated by Django 5.2.11 on 2026-03-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_support_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
