# Generated by Django 5.2.11 on 2026-04-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shared_with_email', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.IntegerField(default=0)),
                ('current_downloads', models.IntegerField(default=0)),
                ('can_download', models.BooleanField(default=True)),
                ('can_view_details', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file_index')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_login')),
            ],
        ),
    ]
