# Generated by Django 5.2.11 on 2026-04-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_notification_ticket_id_sharedlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedlink',
            old_name='last_accessed',
            new_name='accessed_at',
        ),
        migrations.RenameField(
            model_name='sharedlink',
            old_name='can_view_details',
            new_name='can_view',
        ),
        migrations.RemoveField(
            model_name='sharedlink',
            name='current_downloads',
        ),
        migrations.RemoveField(
            model_name='sharedlink',
            name='max_downloads',
        ),
        migrations.RemoveField(
            model_name='sharedlink',
            name='password',
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='shared_with_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_user', to='myapp.user_login'),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_user', to='myapp.user_login'),
        ),
        migrations.AlterModelTable(
            name='sharedlink',
            table='myapp_shared_link',
        ),
    ]
